# Generated by Django 5.2.6 on 2025-09-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_amount_loan_loan_amount_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
    ]
